# Generated by Django 4.1.5 on 2023-01-28 21:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Направление',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_stopped', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('preview_pic', models.ImageField(upload_to='')),
                ('main_pic', models.ImageField(default=0, upload_to='')),
                ('bio', models.TextField()),
                ('video', models.CharField(max_length=1000)),
                ('workouts', models.IntegerField(default=0)),
                ('programs', models.IntegerField(default=0)),
                ('subscribers', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Тренер',
            },
        ),
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Раздел',
            },
        ),
        migrations.CreateModel(
            name='WorkoutProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=30)),
                ('preview_pic', models.ImageField(upload_to='')),
                ('main_pic', models.IntegerField()),
                ('video', models.CharField(max_length=1000)),
                ('length', models.IntegerField(default=0)),
                ('calories', models.IntegerField(default=0)),
                ('amount_of_workouts', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=200)),
                ('level', models.CharField(choices=[('1', 'Новичек'), ('2', 'Любитель'), ('3', 'Продвинутый'), ('4', 'Профессионал')], max_length=1)),
                ('directions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.direction')),
                ('subscribers', models.ManyToManyField(default=0, through='core.Subscription', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='core.trainer')),
            ],
            options={
                'verbose_name': 'Программа',
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(auto_created=True, default=datetime.datetime.now)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=20)),
                ('video', models.CharField(max_length=100)),
                ('picture_src', models.ImageField(upload_to='')),
                ('calories', models.IntegerField(default=0)),
                ('direction', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.direction')),
                ('program', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.workoutprogram')),
                ('trainer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.trainer')),
            ],
            options={
                'verbose_name': 'Тренировка',
            },
        ),
        migrations.AddField(
            model_name='trainer',
            name='direction',
            field=models.ManyToManyField(through='core.Workout', to='core.direction'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='trend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.trend'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workoutprogram'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('mass', models.IntegerField(null=True)),
                ('hips', models.IntegerField(null=True)),
                ('arms', models.IntegerField(null=True)),
                ('chest', models.IntegerField(null=True)),
                ('legs', models.IntegerField(null=True)),
                ('waist', models.IntegerField(null=True)),
                ('prev_pic_front', models.ImageField(default='', null=True, upload_to='')),
                ('cur_pic_front', models.ImageField(default='', null=True, upload_to='')),
                ('prev_pic_back', models.ImageField(default='', null=True, upload_to='')),
                ('cur_pic_back', models.ImageField(default='', null=True, upload_to='')),
                ('prev_pic_side', models.ImageField(default='', null=True, upload_to='')),
                ('cur_pic_side', models.ImageField(default='', null=True, upload_to='')),
                ('last_update', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('name', models.CharField(max_length=20, null=True)),
                ('surname', models.CharField(max_length=20, null=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('instagram', models.CharField(max_length=20, null=True)),
                ('mass', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('sex', models.CharField(max_length=20, null=True)),
                ('birthdate', models.DateField()),
                ('level', models.CharField(choices=[('1', 'Начальный'), ('2', 'Средний'), ('3', 'Эксперт')], default=1, max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_subscribed', models.DateField(auto_created=True)),
                ('num', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('status', models.BooleanField()),
                ('promo', models.CharField(max_length=20, null=True)),
                ('sum', models.IntegerField()),
                ('date_expired', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('preview_pic', models.ImageField(upload_to='')),
                ('main_pic', models.ImageField(upload_to='')),
                ('text', models.TextField()),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('read_time', models.CharField(default='', max_length=5)),
                ('author', models.TextField()),
                ('direction', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.direction')),
            ],
            options={
                'verbose_name': 'Блог',
            },
        ),
    ]
